/* Browser-only, fictional SAAIS records. No network writes or real authentication. */
(function () {
  'use strict';
  const today = '2026-09-19';
  const seed = {
    profiles: [
      {id:'s1',full_name:'Maria Isabel Bautista',student_number:'2023-04412',email:'maria.bautista@example.edu.ph',role:'student',status:'active',department_id:'d1'},
      {id:'s2',full_name:'Angelo Cruz',student_number:'2022-01188',email:'angelo.cruz@example.edu.ph',role:'student',status:'active',department_id:'d1'},
      {id:'s3',full_name:'Joshua Lim',student_number:'2023-02940',email:'joshua.lim@example.edu.ph',role:'student',status:'active',department_id:'d1'},
      {id:'s4',full_name:'Andrea Villanueva',student_number:'2024-00871',email:'andrea.villanueva@example.edu.ph',role:'student',status:'active',department_id:'d1'},
      {id:'a1',full_name:'Prof. Ramon Reyes',email:'ramon.reyes@example.edu.ph',role:'adviser',status:'active',department_id:'d1'},
      {id:'a2',full_name:'Prof. Lourdes Mendez',email:'lourdes.mendez@example.edu.ph',role:'adviser',status:'active',department_id:'d1'},
      {id:'u1',full_name:'Teresa Alvarez',email:'teresa.alvarez@example.edu.ph',role:'admin',status:'active',department_id:'d6'}
    ],
    faculties:[{id:'f1',name:'Faculty of Computer Studies'},{id:'f2',name:'Faculty of Arts and Sciences'},{id:'f3',name:'University Administration'}],
    departments:[{id:'d1',faculty_id:'f1',name:'Computer Science'},{id:'d2',faculty_id:'f1',name:'Information Technology'},{id:'d3',faculty_id:'f2',name:'Mathematics and Statistics'},{id:'d4',faculty_id:'f2',name:'Psychology'},{id:'d5',faculty_id:'f2',name:'General Education'},{id:'d6',faculty_id:'f3',name:'Academic Affairs'}],
    programs:[{id:'p1',code:'BSCS',name:'BS Computer Science',faculty_id:'f1',nominal_duration:'4 years',status:'active'},{id:'p2',code:'BSIT',name:'BS Information Technology',faculty_id:'f1',nominal_duration:'4 years',status:'active'}],
    curricula:[{id:'cv1',program_id:'p1',version_label:'2023–2024',effective_start:'2023-06-01',effective_end:'',delinquency_threshold:12,total_units:156,status:'active'},{id:'cv2',program_id:'p2',version_label:'2024–2025',effective_start:'2024-06-01',effective_end:'',delinquency_threshold:12,total_units:156,status:'active'}],
    curriculumTerms:[{id:'ct1',curriculum_version_id:'cv1',year_level:1,term_sequence:1},{id:'ct2',curriculum_version_id:'cv1',year_level:1,term_sequence:2},{id:'ct3',curriculum_version_id:'cv1',year_level:2,term_sequence:1},{id:'ct4',curriculum_version_id:'cv1',year_level:2,term_sequence:2},{id:'ct5',curriculum_version_id:'cv2',year_level:1,term_sequence:1}],
    courses:[
      ['c1','CS 101','Introduction to Computing',3,'none'],['c2','CS 110','Discrete Computing Structures',3,'none'],['c3','CS 121','Data Structures',3,'grade_replacement'],['c4','CS 122','Object-Oriented Programming',3,'grade_replacement'],['c5','MATH 22','Calculus II',5,'grade_replacement'],['c6','GE 7','Ethics',3,'none'],['c7','PE 3','Team Sports',2,'none'],['c8','STAT 101','Statistics for Computing',3,'grade_replacement'],['c9','CS 132','Design and Analysis of Algorithms',3,'grade_replacement'],['c10','CS 133','Computer Organization',3,'none'],['c11','CS 134','Information Management',3,'none'],['c12','PHILO 12','Logic and Critical Thinking',3,'none'],['c13','MATH 30','Discrete Mathematics',3,'none'],['c14','MATH 31','Discrete Structures',3,'none'],['c15','ENG 1','Communication Skills',3,'none'],['c16','ENGL 101','English Communication (transfer)',3,'none'],['c17','PSYCH 10','General Psychology',3,'none'],['c18','CS 199','Special Topics in Computing',3,'additional_credit']
    ].map(([id,code,title,units,repeatable_type])=>({id,code,title,units,repeatable_type,lecture_hours:3,lab_hours:0,department_id:({c5:'d3',c6:'d5',c7:'d5',c8:'d3',c12:'d5',c13:'d3',c14:'d3',c15:'d5',c16:'d5',c17:'d4'})[id]||'d1',status:id==='c13'?'discontinued':'active'})),
    prerequisites:[{id:'pr1',course_id:'c9',prerequisite_course_id:'c3',type:'strict'},{id:'pr2',course_id:'c9',prerequisite_course_id:'c2',type:'strict'},{id:'pr3',course_id:'c9',prerequisite_course_id:'c4',type:'co_requisite'},{id:'pr4',course_id:'c9',prerequisite_course_id:'c14',type:'recommended'}],
    slots:[['sl1','ct1','c1'],['sl2','ct1','c2'],['sl3','ct1','c15'],['sl4','ct2','c8'],['sl5','ct2','c14'],['sl6','ct3','c3'],['sl7','ct3','c4'],['sl8','ct3','c5'],['sl9','ct3','c6'],['sl10','ct3','c7'],['sl11','ct3',null,'GE ELEC 1'],['sl12','ct4','c9'],['sl13','ct4','c10'],['sl14','ct4','c11'],['sl15','ct4',null,'GE ELEC 2'],['sl16','ct4','c13'],['sl17','ct5','c1']].map(([id,curriculum_term_id,course_id,slot_label])=>({id,curriculum_term_id,course_id,slot_label:slot_label||'',is_elective_slot:!course_id,nominal_units:course_id==='c5'?5:course_id==='c7'?2:3})),
    terms:[{id:'t0',school_year:'2024 - 2025',term_type:'2nd Semester',start_year:2024,end_year:2025,is_locked:true,override_flag:false,override_actor_id:null,override_at:null},{id:'t1',school_year:'2025 - 2026',term_type:'1st Semester',start_year:2025,end_year:2026,is_locked:false,override_flag:false,override_actor_id:null,override_at:null},{id:'t2',school_year:'2025 - 2026',term_type:'2nd Semester',start_year:2025,end_year:2026,is_locked:false,override_flag:false,override_actor_id:null,override_at:null}],
    offerings:[], attempts:[], resolutions:[],
    assignments:[{id:'as0',student_id:'s1',adviser_id:'a2',start_date:'2023-06-01',end_date:'2024-06-12',reason:'Initial assignment'},{id:'as1',student_id:'s1',adviser_id:'a1',start_date:'2024-06-12',end_date:null,reason:'Load rebalancing'},{id:'as2',student_id:'s2',adviser_id:'a1',start_date:'2023-08-05',end_date:null},{id:'as3',student_id:'s3',adviser_id:'a1',start_date:'2024-06-12',end_date:null},{id:'as4',student_id:'s4',adviser_id:'a1',start_date:'2025-06-03',end_date:'2026-08-01'},{id:'as5',student_id:'s4',adviser_id:'a2',start_date:'2026-08-01',end_date:null,reason:'Load rebalancing'}],
    curriculumAssignments:['s1','s2','s3','s4'].map((student_id,i)=>({id:'ca'+i,student_id,curriculum_version_id:'cv1',start_date:'2023-06-01',end_date:null,reason:'Initial assignment'})),
    mappings:[{id:'em1',student_id:'s1',attempt_id:'at6',curriculum_term_course_id:'sl11',units_credited:3,justification:'Approved general education elective.',mapped_by:'a1',created_at:'2026-08-14T09:00:00',updated_at:'2026-08-14T09:00:00'}],
    equivalencies:[{id:'eq1',student_id:'s1',attempt_id:'at7',destination_curriculum_term_course_id:'sl16',decision_type:'discontinued_course_equivalency',units_credited:3,justification:'MATH 31 satisfies discontinued MATH 30.',decided_by:'a1',decided_at:'2026-03-02T09:00:00'},{id:'eq2',student_id:'s1',attempt_id:'at8',destination_curriculum_term_course_id:'sl3',decision_type:'transfer_equivalency',units_credited:3,justification:'Transfer credit reviewed against the syllabus.',decided_by:'a2',decided_at:'2023-11-20T09:00:00'}],
    notes:[{id:'n1',student_id:'s1',authored_by:'a1',body_text:'Discussed a manageable course load. Review the STAT 101 completion requirements before the October deadline.',created_at:'2026-09-17T13:30:00'},{id:'n2',student_id:'s1',authored_by:'a1',body_text:'Reviewed the elective mapping and explained how it appears in the curriculum checklist.',created_at:'2026-08-14T09:00:00'}],
    remarks:[{id:'r1',student_id:'s1',attempt_id:'at3',curriculum_term_course_id:'sl4',authored_by:'a1',body_text:'Completion requirements discussed. Follow up with the instructor before 26 October.',created_at:'2026-09-17T13:35:00'},{id:'r2',student_id:'s1',attempt_id:null,curriculum_term_course_id:'sl12',authored_by:'a1',body_text:'Discuss this course after reviewing CS 121 progress.',created_at:'2026-09-18T09:00:00'}],
    audit:[{id:'au1',actor_id:'a1',action:'elective_mapping.created',entity_type:'ElectiveMapping',entity_id:'em1',old_value:null,new_value:{attempt_id:'at6',curriculum_term_course_id:'sl11'},reason:'Approved general education elective',created_at:'2026-08-14T09:00:00'},{id:'au2',actor_id:'a1',action:'equivalency.approved',entity_type:'EquivalencyDecision',entity_id:'eq1',old_value:null,new_value:{destination_curriculum_term_course_id:'sl16'},created_at:'2026-03-02T09:00:00'},{id:'au3',actor_id:null,action:'gwa.recomputed',entity_type:'Profile',entity_id:'s2',old_value:null,new_value:{is_delinquent:true},created_at:'2026-09-19T02:00:00'},{id:'au4',actor_id:'u1',action:'term.locked',entity_type:'SchoolTerm',entity_id:'t0',old_value:{is_locked:false},new_value:{is_locked:true},created_at:'2026-06-01T09:00:00'}]
  };
  ['t0','t1','t2'].forEach(t=>seed.courses.forEach(c=>{if(t!=='t2'||['c9','c10','c11','c17','c13','c18'].includes(c.id))seed.offerings.push({id:t+'-'+c.id,school_term_id:t,course_id:c.id,is_by_request:c.status==='discontinued'});}));
  const attempts=[['at1','s1','t0','c1','passed',1.25,'sl1'],['at2','s1','t0','c2','passed',1.75,'sl2'],['at3','s1','t0','c8','inc',null,'sl4'],['at4','s1','t0','c5','failed',5,'sl8'],['at5','s1','t0','c17','passed',2,null],['at6','s1','t0','c12','passed',1.75,null],['at7','s1','t0','c14','passed',2.5,null],['at8','s1','t0','c16','passed',1.5,null],...['c3','c4','c5','c6','c7'].map((c,i)=>['at'+(9+i),'s1','t1',c,'currently_enrolled',null,'sl'+(6+i)]),['at20','s2','t0','c1','passed',2,'sl1'],['at21','s2','t1','c3','failed',5,'sl6'],['at22','s2','t1','c4','failed',5,'sl7'],['at23','s2','t1','c8','inc',null,'sl4'],['at24','s2','t1','c6','failed',5,'sl9'],['at30','s3','t0','c3','inc',null,'sl6'],['at31','s3','t0','c1','passed',1.5,'sl1'],['at40','s4','t0','c1','passed',1.75,'sl1']];
  seed.attempts=attempts.map(([id,student_id,t,c,status,final_grade,curriculum_term_course_id])=>({id,student_id,course_offering_id:t+'-'+c,curriculum_term_course_id,status,final_grade,midterm_grade:final_grade,inc_deadline:status==='inc'?(id==='at23'?'2026-09-01':id==='at30'?'2026-09-21':'2026-10-26'):null,prerequisite_override:false,prerequisite_override_reason:'',created_at:t==='t0'?'2025-06-09T09:00:00':'2026-06-08T09:00:00',updated_at:'2026-09-08T09:00:00'}));
  const key='saais-demo-v4';
  let db;try{db=JSON.parse(localStorage.getItem(key))||structuredClone(seed);}catch{db=structuredClone(seed);}
  // Restore the sample 'recommended' prerequisite once for browsers that saved data while it was removed.
  if(!db._recommendedRestored){if(!db.prerequisites.some(p=>p.id==='pr4'))db.prerequisites.push({id:'pr4',course_id:'c9',prerequisite_course_id:'c14',type:'recommended'});db._recommendedRestored=true;}
  const find=(table,id)=>db[table].find(x=>x.id===id);
  // Terms carry only start/end years. Order and INC defaults are derived from them and the term type.
  const termOrder={'1st Semester':1,'2nd Semester':2,'Summer':3};
  const termKey=t=>t.start_year*10+(termOrder[t.term_type]||0);
  const termEndDate=t=>{const [m,d]={'1st Semester':[10,31],'2nd Semester':[3,31],'Summer':[7,31]}[t.term_type]||[12,31];return `${t.term_type==='1st Semester'?t.start_year:t.end_year}-${String(m).padStart(2,'0')}-${d}`;};
  const schoolYear=(type,start,end)=>type==='Summer'?`${end-1} - ${end}`:`${start} - ${end}`;
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
  const save=()=>{try{localStorage.setItem(key,JSON.stringify(db));return true;}catch{return false;}};
  const grade=a=>{const r=db.resolutions.find(r=>r.attempt_id===a.id);if(r)return Number(r.completion_grade);if(a.status==='inc')return a.inc_deadline<today?5:null;return ['passed','failed'].includes(a.status)?Number(a.final_grade):null;};
  const course=a=>find('courses',find('offerings',a.course_offering_id)?.course_id);
  const passed=a=>a.status==='passed'||(a.status==='inc'&&db.resolutions.some(r=>r.attempt_id===a.id&&Number(r.completion_grade)<=3));
  const metrics=(student,term)=>{
    const rows=db.attempts.filter(a=>a.student_id===student&&(!term||find('offerings',a.course_offering_id)?.school_term_id===term));
    let counted=[];
    for(const c of db.courses){const list=rows.filter(a=>course(a)?.id===c.id).sort((a,b)=>{const ta=termKey(find('terms',find('offerings',a.course_offering_id).school_term_id));const tb=termKey(find('terms',find('offerings',b.course_offering_id).school_term_id));return (ta-tb)||a.created_at.localeCompare(b.created_at);});const ps=list.filter(passed);if(c.repeatable_type==='additional_credit')counted.push(...ps);else if(ps.length)counted.push(ps.at(-1));else if(list.length)counted.push(list.at(-1));}
    let units=0,weighted=0,earned=0,failed=0;
    counted.forEach(a=>{const g=grade(a),u=Number(course(a).units);if(g!==null){units+=u;weighted+=g*u;}if(passed(a))earned+=u;if(g!==null&&g>3)failed+=u;});
    const ca=db.curriculumAssignments.find(a=>a.student_id===student&&!a.end_date);const cv=find('curricula',ca?.curriculum_version_id);const threshold=Number(cv?.delinquency_threshold||12);
    const delinquent=term?failed>=threshold:db.terms.some(t=>metrics(student,t.id).failed>=threshold);
    return {gwa:units?(weighted/units).toFixed(2):'—',units,earned,failed,delinquent,threshold,total:cv?.total_units||156};
  };
  const audit=(actor,action,entity_type,entity_id,old_value,new_value,reason='')=>db.audit.unshift({id:uid(),actor_id:actor,action,entity_type,entity_id,old_value:old_value?structuredClone(old_value):null,new_value:new_value?structuredClone(new_value):null,reason,created_at:new Date().toISOString()});
  window.SAAIS={get db(){return db;},find,termKey,termEndDate,schoolYear,uid,save,grade,course,passed,metrics,audit,today,reset(){db=structuredClone(seed);save();},seed};
})();
