from pathlib import Path
p=Path(__file__).parent
s=(p/'product.js').read_text(encoding='utf-8')
s=s.replace('<aside class="side" id="app-navigation"><a', '<aside class="side" id="app-navigation"><button class="mobile-menu drawer-close" data-action="menu">Close navigation</button><a')
s=s.replace("if(kind==='program')used=M.db.curricula.some(c=>c.program_id===id);", "if(kind==='program')used=M.db.curricula.some(c=>c.program_id===id&&M.db.curriculumAssignments.some(a=>a.curriculum_version_id===c.id));")
s=s.replace("if(kind==='curriculum'){const ids=", "if(kind==='program'){const cvs=M.db.curricula.filter(c=>c.program_id===id).map(c=>c.id);const ts=M.db.curriculumTerms.filter(t=>cvs.includes(t.curriculum_version_id)).map(t=>t.id);M.db.slots=M.db.slots.filter(s=>!ts.includes(s.curriculum_term_id));M.db.curriculumTerms=M.db.curriculumTerms.filter(t=>!cvs.includes(t.curriculum_version_id));M.db.curricula=M.db.curricula.filter(c=>c.program_id!==id);}\nif(kind==='curriculum'){const ids=")
(p/'product.js').write_text(s,encoding='utf-8')
s=(p/'gen_marketing.py').read_text(encoding='utf-8')
s=s.replace('f\'<div style="padding: 12px 26px 13px; font-size: 15px; \',','f\'<button data-landing-tab="{label}" aria-pressed="{str(on).lower()}" style="background: transparent; border: 0; font-family: inherit; padding: 12px 26px 13px; font-size: 15px; \',')
s=s.replace('tb += (f\'<div style="padding: 12px 26px 13px;', 'tb += (f\'<button data-landing-tab="{label}" aria-pressed="{str(on).lower()}" style="background: transparent; border: 0; font-family: inherit; padding: 12px 26px 13px;')
s=s.replace('{bar}">{label}</div>', '{bar}">{label}</button>')
s=s.replace('+ f\'<div style="display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1.2fr);', '+ f\'<div id="landing-feature-panel" style="display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1.2fr);')
s=s.replace('tb += (f\'<div style="padding: 10px 22px;', 'tb += (f\'<button data-landing-step="{n}" aria-pressed="{str(on).lower()}" style="font-family: inherit; padding: 10px 22px;')
s=s.replace('{st}">{n}</div>', '{st}">{n}</button>')
s=s.replace('panel = (f\'<div style="background:', 'panel = (f\'<div id="landing-step-panel" style="background:')
s=s.replace('pill("Sign up",', 'pill("View release notes",')
(p/'gen_marketing.py').write_text(s,encoding='utf-8')
s=(p/'demo-model.js').read_text(encoding='utf-8').replace("['at7','s1','t0','c14','passed',2.5,'sl5']", "['at7','s1','t0','c14','passed',2.5,null]")
(p/'demo-model.js').write_text(s,encoding='utf-8')
